#!/usr/bin/env python3
"""
Interactive setup script for configuring API keys in your chosen secrets manager.

This script helps you:
1. Choose your secrets provider (env, aws, azure, gcp)
2. Enter your API keys securely
3. Store them in the selected provider
4. Configure team access

Usage:
    python scripts/setup_secrets.py
"""

import os
import sys
import getpass
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from pulsepilot.core.secrets import SecretsManagerFactory, SecretProvider


def print_header(text):
    """Print a section header."""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")


def get_choice(prompt, options):
    """Get user choice from options."""
    print(prompt)
    for i, option in enumerate(options, 1):
        print(f"  {i}. {option}")

    while True:
        try:
            choice = int(input("\nEnter choice (number): "))
            if 1 <= choice <= len(options):
                return options[choice - 1]
            print(f"Please enter a number between 1 and {len(options)}")
        except ValueError:
            print("Please enter a valid number")
        except KeyboardInterrupt:
            print("\n\nSetup cancelled.")
            sys.exit(0)


def get_secret_value(name, optional=False, current_value=None):
    """Prompt for a secret value."""
    prompt = f"{name}"
    if optional:
        prompt += " (optional, press Enter to skip)"
    if current_value:
        prompt += f" (current: {current_value[:10]}...)"
    prompt += ": "

    value = getpass.getpass(prompt)
    return value if value else None


def setup_env_provider():
    """Set up environment variable provider."""
    print_header("Environment Variables Setup")

    print("This will create a .env file in your project root.")
    print("⚠️  Environment variables are NOT secure for production!")
    print("    Use this only for local development.\n")

    env_file = Path(__file__).parent.parent / ".env"

    if env_file.exists():
        overwrite = input(f"\n.env file already exists. Overwrite? (y/N): ")
        if overwrite.lower() != 'y':
            print("Setup cancelled.")
            return

    # Collect secrets
    secrets = {}

    print("\nEnter your API keys:")
    secrets['OPENAI_API_KEY'] = get_secret_value("OpenAI API Key", optional=True)
    secrets['ANTHROPIC_API_KEY'] = get_secret_value("Anthropic API Key", optional=True)
    secrets['TELEGRAM_BOT_TOKEN'] = get_secret_value("Telegram Bot Token", optional=True)

    if secrets.get('TELEGRAM_BOT_TOKEN'):
        secrets['TELEGRAM_CHAT_ID'] = input("Telegram Chat ID: ") or None

    # Write .env file
    with open(env_file, 'w') as f:
        f.write("# PulsePilot Secrets Configuration\n")
        f.write("# Generated by setup_secrets.py\n\n")
        f.write("SECRETS_PROVIDER=env\n\n")

        for key, value in secrets.items():
            if value:
                f.write(f"{key}={value}\n")

    print(f"\n✅ Secrets saved to {env_file}")
    print("\n⚠️  IMPORTANT:")
    print("   - Never commit .env to Git (already in .gitignore)")
    print("   - Share .env securely with team (1Password, encrypted email, etc.)")
    print("\nNext steps:")
    print("   1. Run: poetry install")
    print("   2. Test: python examples/secure_secrets_example.py")


def setup_aws_provider():
    """Set up AWS Secrets Manager."""
    print_header("AWS Secrets Manager Setup")

    try:
        import boto3
    except ImportError:
        print("❌ boto3 not installed.")
        print("   Run: poetry install -E aws")
        return

    # Check AWS credentials
    try:
        sts = boto3.client('sts')
        identity = sts.get_caller_identity()
        print(f"✓ AWS credentials configured")
        print(f"  Account: {identity['Account']}")
        print(f"  User: {identity['Arn']}")
    except Exception as e:
        print(f"❌ AWS credentials not configured: {e}")
        print("   Run: aws configure")
        return

    # Get region
    region = input(f"\nAWS Region (default: us-east-1): ") or "us-east-1"

    # Create secrets manager
    try:
        sm = SecretsManagerFactory.create(
            SecretProvider.AWS,
            region_name=region
        )
    except Exception as e:
        print(f"❌ Failed to connect to AWS Secrets Manager: {e}")
        return

    # Collect and store secrets
    print("\nEnter your API keys:")

    secrets_to_add = [
        ("OPENAI_API_KEY", "OpenAI API Key", True),
        ("ANTHROPIC_API_KEY", "Anthropic API Key", True),
        ("TELEGRAM_BOT_TOKEN", "Telegram Bot Token", True),
        ("TELEGRAM_CHAT_ID", "Telegram Chat ID", True),
    ]

    stored_count = 0
    for secret_name, display_name, optional in secrets_to_add:
        value = get_secret_value(display_name, optional=optional)
        if value:
            try:
                sm.set_secret(secret_name, value)
                print(f"  ✓ {secret_name} stored")
                stored_count += 1
            except Exception as e:
                print(f"  ❌ Failed to store {secret_name}: {e}")

    # Create .env file with AWS config
    env_file = Path(__file__).parent.parent / ".env"
    with open(env_file, 'w') as f:
        f.write("# PulsePilot AWS Secrets Manager Configuration\n\n")
        f.write("SECRETS_PROVIDER=aws\n")
        f.write(f"AWS_DEFAULT_REGION={region}\n")

    print(f"\n✅ Stored {stored_count} secrets in AWS Secrets Manager")
    print(f"✅ Configuration saved to .env")

    print("\n📋 Team Setup Instructions:")
    print("   1. Configure AWS credentials: aws configure")
    print("   2. Install AWS support: poetry install -E aws")
    print("   3. Copy .env file (contains only SECRETS_PROVIDER=aws)")
    print("   4. Attach IAM policy (see docs/SECURITY.md)")


def setup_azure_provider():
    """Set up Azure Key Vault."""
    print_header("Azure Key Vault Setup")

    try:
        from azure.keyvault.secrets import SecretClient
        from azure.identity import DefaultAzureCredential
    except ImportError:
        print("❌ Azure packages not installed.")
        print("   Run: poetry install -E azure")
        return

    vault_url = input("\nAzure Key Vault URL (https://your-vault.vault.azure.net/): ")
    if not vault_url:
        print("❌ Vault URL required")
        return

    # Test connection
    try:
        sm = SecretsManagerFactory.create(
            SecretProvider.AZURE,
            vault_url=vault_url
        )
    except Exception as e:
        print(f"❌ Failed to connect to Azure Key Vault: {e}")
        print("   Run: az login")
        return

    print("✓ Connected to Azure Key Vault")

    # Collect and store secrets
    print("\nEnter your API keys:")
    print("⚠️  Note: Azure Key Vault uses hyphens instead of underscores")

    secrets_to_add = [
        ("OPENAI-API-KEY", "OpenAI API Key", True),
        ("ANTHROPIC-API-KEY", "Anthropic API Key", True),
        ("TELEGRAM-BOT-TOKEN", "Telegram Bot Token", True),
        ("TELEGRAM-CHAT-ID", "Telegram Chat ID", True),
    ]

    stored_count = 0
    for secret_name, display_name, optional in secrets_to_add:
        value = get_secret_value(display_name, optional=optional)
        if value:
            try:
                sm.set_secret(secret_name, value)
                print(f"  ✓ {secret_name} stored")
                stored_count += 1
            except Exception as e:
                print(f"  ❌ Failed to store {secret_name}: {e}")

    # Create .env file
    env_file = Path(__file__).parent.parent / ".env"
    with open(env_file, 'w') as f:
        f.write("# PulsePilot Azure Key Vault Configuration\n\n")
        f.write("SECRETS_PROVIDER=azure\n")
        f.write(f"AZURE_KEY_VAULT_URL={vault_url}\n")

    print(f"\n✅ Stored {stored_count} secrets in Azure Key Vault")
    print(f"✅ Configuration saved to .env")

    print("\n📋 Team Setup Instructions:")
    print("   1. Authenticate: az login")
    print("   2. Install Azure support: poetry install -E azure")
    print("   3. Copy .env file")
    print("   4. Grant 'Key Vault Secrets User' role")


def setup_gcp_provider():
    """Set up Google Cloud Secret Manager."""
    print_header("Google Cloud Secret Manager Setup")

    try:
        from google.cloud import secretmanager
    except ImportError:
        print("❌ Google Cloud packages not installed.")
        print("   Run: poetry install -E gcp")
        return

    project_id = input("\nGCP Project ID: ")
    if not project_id:
        print("❌ Project ID required")
        return

    # Test connection
    try:
        sm = SecretsManagerFactory.create(
            SecretProvider.GCP,
            project_id=project_id
        )
    except Exception as e:
        print(f"❌ Failed to connect to GCP Secret Manager: {e}")
        print("   Run: gcloud auth application-default login")
        return

    print("✓ Connected to GCP Secret Manager")

    # Collect and store secrets
    print("\nEnter your API keys:")

    secrets_to_add = [
        ("OPENAI_API_KEY", "OpenAI API Key", True),
        ("ANTHROPIC_API_KEY", "Anthropic API Key", True),
        ("TELEGRAM_BOT_TOKEN", "Telegram Bot Token", True),
        ("TELEGRAM_CHAT_ID", "Telegram Chat ID", True),
    ]

    stored_count = 0
    for secret_name, display_name, optional in secrets_to_add:
        value = get_secret_value(display_name, optional=optional)
        if value:
            try:
                sm.set_secret(secret_name, value)
                print(f"  ✓ {secret_name} stored")
                stored_count += 1
            except Exception as e:
                print(f"  ❌ Failed to store {secret_name}: {e}")

    # Create .env file
    env_file = Path(__file__).parent.parent / ".env"
    with open(env_file, 'w') as f:
        f.write("# PulsePilot GCP Secret Manager Configuration\n\n")
        f.write("SECRETS_PROVIDER=gcp\n")
        f.write(f"GCP_PROJECT_ID={project_id}\n")

    print(f"\n✅ Stored {stored_count} secrets in GCP Secret Manager")
    print(f"✅ Configuration saved to .env")

    print("\n📋 Team Setup Instructions:")
    print("   1. Authenticate: gcloud auth application-default login")
    print("   2. Install GCP support: poetry install -E gcp")
    print("   3. Copy .env file")
    print("   4. Grant 'Secret Manager Secret Accessor' role")


def main():
    """Main setup flow."""
    print_header("PulsePilot Secrets Management Setup")

    print("Welcome! This script will help you set up secure API key management.")
    print("\nWhere do you want to store your API keys?")

    provider_choice = get_choice(
        "",
        [
            "Environment Variables (.env file) - Local development only",
            "AWS Secrets Manager - Production (AWS cloud)",
            "Azure Key Vault - Production (Azure cloud)",
            "Google Cloud Secret Manager - Production (GCP cloud)"
        ]
    )

    if "Environment" in provider_choice:
        setup_env_provider()
    elif "AWS" in provider_choice:
        setup_aws_provider()
    elif "Azure" in provider_choice:
        setup_azure_provider()
    elif "Google" in provider_choice:
        setup_gcp_provider()

    print("\n" + "=" * 60)
    print("  Setup Complete! 🎉")
    print("=" * 60)
    print("\nFor more information, see:")
    print("  - docs/SECURITY.md (full documentation)")
    print("  - docs/QUICKSTART_SECURITY.md (quick start guide)")
    print("  - examples/secure_secrets_example.py (code examples)")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
